name: 'Update Profile README'
author: 'Prachi Jamdade'
description: 'Fetch recent or top articles from RSS feeds and update the user profile README.'
inputs:
  feed_urls:
    description: 'Comma-separated list of RSS feed URLs'
    required: true
  article_limit:
    description: 'Number of articles to fetch. Use 0 or negative number to fetch recent articles only.'
    required: true
    default: 5
  article_type:
    description: 'Type of articles to fetch: "recent" or "top".'
    required: true
    default: 'recent'
  github_token:
    description: 'GitHub token for authentication'
    required: true
  hashnode_token:
    description: 'Hashnode token for authentication'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.feed_urls }}
    - ${{ inputs.article_limit }}
    - ${{ inputs.article_type }}
    - ${{ inputs.github_token }}
    - ${{ inputs.hashnode_token }}
branding:
  icon: 'align-right'
  color: 'blue'